### PR TITLE
Plugin to prettifier code

### PR DESCRIPTION
**Pull request by pangea-andrest**
- Key change is on pom.xml

### CODE REVIEW

**Comment by r3dcrosse** [comment]
Our gitlab pipeline is failing to install prettier-maven-plugin with this error:
```
x86_64-binfmt-P: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
```

We're using this docker image in our CI/CD: `maven:3-openjdk-18`

Locally I think we're all using `openjdk-19.0.1` so I think our pipeline is failing because it's on openjdk 18 instead of 19?

From this issue: https://github.com/carlossg/docker-maven/issues/305 the openjdk image has been deprecated, so there is no openjdk-19 image.

We may want to switch to one of the images to get jdk 19:

- [maven:3-eclipse-temurin-19](https://github.com/carlossg/docker-maven/blob/34e7d27260ee61c6866922c523e04b53ba098337/eclipse-temurin-19/Dockerfile)
- [maven:3-amazoncorretto-19](https://github.com/carlossg/docker-maven/blob/34e7d27260ee61c6866922c523e04b53ba098337/amazoncorretto-19/Dockerfile)

Full list of official maven images: https://hub.docker.com/_/maven

I'll open a pull request switching the docker image we use in CI/CD to see if that can help move us forward.

**Comment by r3dcrosse** [comment]
Pull request for switching to a docker image that has jdk-19: https://github.com/pangeacyber/pangea-java/pull/52

**Comment by r3dcrosse** [comment]
> Pull request for switching to a docker image that has jdk-19: #52

This did not fix the issue: https://github.com/pangeacyber/pangea-java/pull/54

still failing on
```
x86_64-binfmt-P: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
```

I'm not sure what to do past this point?

**Comment by doubletooth** [comment]
linux-x86-64 means it's looking for an x86 runner, not arm

**Comment by pangea-andrest** [comment]
@doubletooth @r3dcrosse based on:
https://stackoverflow.com/questions/68630526/lib64-ld-linux-x86-64-so-2-no-such-file-or-directory-error 
adding `docker run --platform linux/x86_64 <image>` could fix it? 
Not sure if we should change runner and if that's possible, of if we change it only to run this pipeline.

**Comment by pangea-andrest** [comment]
Handled on https://github.com/pangeacyber/pangea-java/pull/64

**Pull request closed without merging**
